### PR TITLE
Now works on puppet 3.6

### PR DESCRIPTION
**Pull request by hajee**
It now works without syntax errors. Still having problems with my original case.

``` puppet
  network_config { 'eth2':
    ensure    => 'present',
    family    => 'inet',
    method    => 'static',
    onboot    => 'true',
    hotplug   => 'true',
    ipaddress => $private_ipaddress,
    netmask   => '255.255.255.0',
  } ~>

  service{'network':
    ensure  => 'running',
  } ~>

  refacter{'define_eth2_facts':
    patterns => [ "network" ],
  }
```

Somehow the new network facts for eth2 are not picked up.Any help or suggestions are welcome!

### CODE REVIEW

**Comment by hajee** [comment]
@breml You are the king. Your proposed changes work like a charm

**Comment by hajee** [comment]
@hercynium It would be beneficial for me if you can publish this module on the puppet forge. This means I can easily use them from a Puppefile. 

Do you have any plans to do so?

**Comment by breml** [comment]
Thanks, glad I could help.

**Comment by hajee** [comment]
@hercynium 
Steven, do you have a timeframe in mind when you have time to look at the PR?

**Comment by hajee** [comment]
I've run into some issue's. I would like your opinion on. The reloading works fine, but it run's the whole manifest twice. After the message `finished reloading puppet to pick up new facts`, it continue's where it left off and runs the rest of the manifest. 

A problem that occurs is that custum types that use prefetching, get the state before the reload, but continue their actions after the reload, based on a state that is altered whithin the reload. (Yes I know it sounds difficult, because it is :-))

The code right now is:

```ruby
Puppet.alert("reloading puppet to pick up new facts")
Puppet::Application.restart!
pconf.run
Puppet.alert("finished reloading puppet to pick up new facts")
````

When I change it to:

```ruby
Puppet.alert("reloading puppet to pick up new facts")
pconf.run
Puppet::Application.stop!
Puppet.alert("finished reloading puppet to pick up new facts")
```

It seems to work. My reasoning is. `pconf.run` reloads the **whole** manifest from begin to end including new facts. There is no need to continue running the remainder of the manifest after puppet is finished.

Is this good thinking, or am I missing something.

Bert

**Comment by breml** [comment]
@hajee My opinion is, we should interrupt the first run as you propose, but I haven't tested your code and therefore I can't tell if there are unwandted sideeffects.
Especial we should test what happens, if refacter is run more than once during one manifest.

**Comment by hajee** [comment]
@hercynium  Can you please give an estimate on when you have time? If this module is not in your intrest anymore, I would be more than happy to to take over maintenance.

**Comment by hajee** [comment]
@breml I'll make some test cases for this.

**Pull request closed without merging**
